//QUERIES
export const FETCH_ALL_DISHES = "FETCH_ALL_DISHES";
export const FETCH_CREATED_DISHES = "FETCH_CREATED_DISHES";

//MUTATIONS
export const CREATE_NEW_DISH = "CREATE_NEW_DISH";
export const CREATE_NEW_USER = "CREATE_NEW_USER";
export const DELETE_DISH = "DELETE_DISH";
export const LOGIN = "LOGIN";
