//QUERIES
export const FETCH_ALL_DISHES = "FETCH_ALL_DISHES";
export const FETCH_CREATED_DISHES = "FETCH_CREATED_DISHES";
export const FETCH_DISH_BY_ID = "FETCH_DISH_BY_ID";
export const FETCH_ALL_USERS = "FETCH_ALL_USERS";
export const FETCH_USER_BY_ID = "FETCH_USER_BY_ID";
export const FETCH_DISH_BY_NAME = "FETCH_DISH_BY_NAME";

//MUTATIONS
export const CREATE_NEW_DISH = "CREATE_NEW_DISH";
export const CREATE_NEW_USER = "CREATE_NEW_USER";
export const DELETE_DISH = "DELETE_DISH";
export const LOGIN = "LOGIN";
